// <auto-generated />
using FantasyHOF.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyHOF.EntityFramework.Migrations
{
    [DbContext(typeof(FantasyHOFDBContext))]
    [Migration("20251217164843_UnknownPos")]
    partial class UnknownPos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyHOF.Domain.Types.AccumulatedStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchupRosterSpotId")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_roster_spot_id");

                    b.Property<decimal>("PointsScored")
                        .HasColumnType("numeric")
                        .HasColumnName("points_scored");

                    b.Property<int>("StatId")
                        .HasColumnType("integer")
                        .HasColumnName("stat_id");

                    b.Property<decimal>("StatValue")
                        .HasColumnType("numeric")
                        .HasColumnName("stat_value");

                    b.HasKey("Id")
                        .HasName("pk_accumulated_stats");

                    b.HasIndex("MatchupRosterSpotId")
                        .HasDatabaseName("ix_accumulated_stats_matchup_roster_spot_id");

                    b.HasIndex("StatId")
                        .HasDatabaseName("ix_accumulated_stats_stat_id");

                    b.ToTable("accumulated_stats", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.FantasyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("FantasyProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("fantasy_provider_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("ProviderMemberId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_member_id");

                    b.HasKey("Id")
                        .HasName("pk_fantasy_members");

                    b.HasIndex("FantasyProviderId", "ProviderMemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_fantasy_members_fantasy_provider_id_provider_member_id");

                    b.ToTable("fantasy_members", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.FantasyProvider", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fantasy_providers");

                    b.ToTable("fantasy_providers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ESPN"
                        });
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FantasyProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("fantasy_provider_id");

                    b.Property<string>("ProviderLeagueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_league_id");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.HasKey("Id")
                        .HasName("pk_leagues");

                    b.HasIndex("FantasyProviderId")
                        .HasDatabaseName("ix_leagues_fantasy_provider_id");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_league_seasons");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_league_seasons_league_id");

                    b.ToTable("league_seasons", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMember", b =>
                {
                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<bool>("IsLeagueCreator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_league_creator");

                    b.Property<bool>("IsLeagueManager")
                        .HasColumnType("boolean")
                        .HasColumnName("is_league_manager");

                    b.HasKey("LeagueSeasonId", "MemberId")
                        .HasName("pk_league_season_members");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_league_season_members_member_id");

                    b.ToTable("league_season_members", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMemberTeam", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.HasKey("MemberId", "TeamId")
                        .HasName("pk_league_season_member_teams");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_league_season_member_teams_team_id");

                    b.HasIndex("LeagueSeasonId", "MemberId")
                        .HasDatabaseName("ix_league_season_member_teams_league_season_id_member_id");

                    b.ToTable("league_season_member_teams", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScheduleSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<int>("MatchupCount")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_count");

                    b.Property<int>("MatchupLength")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_length");

                    b.Property<int>("PlayoffMatchupLength")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_matchup_length");

                    b.Property<int>("PlayoffTeamCount")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_team_count");

                    b.Property<bool>("VariablePlayoffMatchupLength")
                        .HasColumnType("boolean")
                        .HasColumnName("variable_playoff_matchup_length");

                    b.HasKey("Id")
                        .HasName("pk_league_season_schedule_settings");

                    b.HasIndex("LeagueSeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_season_schedule_settings_league_season_id");

                    b.ToTable("league_season_schedule_settings", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric")
                        .HasColumnName("points");

                    b.Property<int>("StatId")
                        .HasColumnType("integer")
                        .HasColumnName("stat_id");

                    b.HasKey("Id")
                        .HasName("pk_league_season_scoring_items");

                    b.HasIndex("LeagueSeasonId")
                        .HasDatabaseName("ix_league_season_scoring_items_league_season_id");

                    b.HasIndex("StatId")
                        .HasDatabaseName("ix_league_season_scoring_items_stat_id");

                    b.ToTable("league_season_scoring_items", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HomeTeamBonusPoints")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_bonus_points");

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<string>("MatchupTieRule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matchup_tie_rule");

                    b.Property<int>("MatchupTieRuleBy")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_tie_rule_by");

                    b.Property<string>("PlayerRankType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_rank_type");

                    b.Property<int>("PlayoffHomeTeamBonusPoints")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_home_team_bonus_points");

                    b.Property<string>("PlayoffMatchupTieRule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("playoff_matchup_tie_rule");

                    b.Property<int>("PlayoffMatchupTieRuleBy")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_matchup_tie_rule_by");

                    b.Property<string>("ScoringType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scoring_type");

                    b.HasKey("Id")
                        .HasName("pk_league_season_scoring_settings");

                    b.HasIndex("LeagueSeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_season_scoring_settings_league_season_id");

                    b.ToTable("league_season_scoring_settings", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("league_name");

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.HasKey("Id")
                        .HasName("pk_league_season_settings");

                    b.HasAlternateKey("LeagueSeasonId")
                        .HasName("ak_league_season_settings_league_season_id");

                    b.ToTable("league_season_settings", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.MatchupRosterSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchupId")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<decimal>("PointsScored")
                        .HasColumnType("numeric")
                        .HasColumnName("points_scored");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.HasKey("Id")
                        .HasName("pk_matchup_roster_spots");

                    b.HasIndex("MatchupId")
                        .HasDatabaseName("ix_matchup_roster_spots_matchup_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_matchup_roster_spots_player_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_matchup_roster_spots_position_id");

                    b.ToTable("matchup_roster_spots", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<int>("ProviderPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_player_id");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("ProviderId", "ProviderPlayerId")
                        .HasDatabaseName("ix_players_provider_id_provider_player_id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Position", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.ToTable("positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "QB"
                        },
                        new
                        {
                            Id = 1,
                            Name = "TQB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RB"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RBWR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "WR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "WRTE"
                        },
                        new
                        {
                            Id = 6,
                            Name = "TE"
                        },
                        new
                        {
                            Id = 7,
                            Name = "OP"
                        },
                        new
                        {
                            Id = 8,
                            Name = "DT"
                        },
                        new
                        {
                            Id = 9,
                            Name = "DE"
                        },
                        new
                        {
                            Id = 10,
                            Name = "LB"
                        },
                        new
                        {
                            Id = 11,
                            Name = "DL"
                        },
                        new
                        {
                            Id = 12,
                            Name = "CB"
                        },
                        new
                        {
                            Id = 13,
                            Name = "S"
                        },
                        new
                        {
                            Id = 14,
                            Name = "DB"
                        },
                        new
                        {
                            Id = 15,
                            Name = "DP"
                        },
                        new
                        {
                            Id = 16,
                            Name = "DST"
                        },
                        new
                        {
                            Id = 17,
                            Name = "K"
                        },
                        new
                        {
                            Id = 18,
                            Name = "P"
                        },
                        new
                        {
                            Id = 19,
                            Name = "HC"
                        },
                        new
                        {
                            Id = 20,
                            Name = "BE"
                        },
                        new
                        {
                            Id = 21,
                            Name = "IR"
                        },
                        new
                        {
                            Id = 23,
                            Name = "RBWRTE"
                        },
                        new
                        {
                            Id = 24,
                            Name = "ER"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Rookie"
                        },
                        new
                        {
                            Id = 999,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Stat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_stats");

                    b.ToTable("stats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "AttemptedPasses"
                        },
                        new
                        {
                            Id = 1,
                            Name = "CompletedPasses"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IncompletePasses"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PassingYards"
                        },
                        new
                        {
                            Id = 4,
                            Name = "PassingTouchdowns"
                        },
                        new
                        {
                            Id = 5,
                            Name = "PassingYardsPer5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "PassingYardsPer10"
                        },
                        new
                        {
                            Id = 7,
                            Name = "PassingYardsPer20"
                        },
                        new
                        {
                            Id = 8,
                            Name = "PassingYardsPer25"
                        },
                        new
                        {
                            Id = 9,
                            Name = "PassingYardsPer50"
                        },
                        new
                        {
                            Id = 10,
                            Name = "PassingYardsPer100"
                        },
                        new
                        {
                            Id = 11,
                            Name = "PassCompletionsPer5"
                        },
                        new
                        {
                            Id = 12,
                            Name = "PassCompletionsPer10"
                        },
                        new
                        {
                            Id = 13,
                            Name = "PassIncompletionsPer5"
                        },
                        new
                        {
                            Id = 14,
                            Name = "PassIncompletionsPer10"
                        },
                        new
                        {
                            Id = 15,
                            Name = "PassingTD40PlusBonus"
                        },
                        new
                        {
                            Id = 16,
                            Name = "PassingTD50PlusBonus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Passing300To399YardGame"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Passing400PlusYardGame"
                        },
                        new
                        {
                            Id = 19,
                            Name = "PassingTwoPointConversion"
                        },
                        new
                        {
                            Id = 20,
                            Name = "InterceptionsThrown"
                        },
                        new
                        {
                            Id = 21,
                            Name = "CompletionPercentage"
                        },
                        new
                        {
                            Id = 22,
                            Name = "PassingYardsPerGame"
                        },
                        new
                        {
                            Id = 23,
                            Name = "RushingAttempts"
                        },
                        new
                        {
                            Id = 24,
                            Name = "RushingYards"
                        },
                        new
                        {
                            Id = 25,
                            Name = "RushingTouchdowns"
                        },
                        new
                        {
                            Id = 26,
                            Name = "RushingTwoPointConversion"
                        },
                        new
                        {
                            Id = 27,
                            Name = "RushingYardsPer5"
                        },
                        new
                        {
                            Id = 28,
                            Name = "RushingYardsPer10"
                        },
                        new
                        {
                            Id = 29,
                            Name = "RushingYardsPer20"
                        },
                        new
                        {
                            Id = 30,
                            Name = "RushingYardsPer25"
                        },
                        new
                        {
                            Id = 31,
                            Name = "RushingYardsPer50"
                        },
                        new
                        {
                            Id = 32,
                            Name = "RushingYardsPer100"
                        },
                        new
                        {
                            Id = 33,
                            Name = "RushingAttemptsPer5"
                        },
                        new
                        {
                            Id = 34,
                            Name = "RushingAttemptsPer10"
                        },
                        new
                        {
                            Id = 35,
                            Name = "RushingTD40PlusBonus"
                        },
                        new
                        {
                            Id = 36,
                            Name = "RushingTD50PlusBonus"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Rushing100To199YardGame"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Rushing200PlusYardGame"
                        },
                        new
                        {
                            Id = 39,
                            Name = "RushingYardsPerAttempt"
                        },
                        new
                        {
                            Id = 40,
                            Name = "RushingYardsPerGame"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Receptions"
                        },
                        new
                        {
                            Id = 42,
                            Name = "ReceivingYards"
                        },
                        new
                        {
                            Id = 43,
                            Name = "ReceivingTouchdowns"
                        },
                        new
                        {
                            Id = 44,
                            Name = "ReceivingTwoPointConversion"
                        },
                        new
                        {
                            Id = 45,
                            Name = "ReceivingTD40PlusBonus"
                        },
                        new
                        {
                            Id = 46,
                            Name = "ReceivingTD50PlusBonus"
                        },
                        new
                        {
                            Id = 47,
                            Name = "ReceivingYardsPer5"
                        },
                        new
                        {
                            Id = 48,
                            Name = "ReceivingYardsPer10"
                        },
                        new
                        {
                            Id = 49,
                            Name = "ReceivingYardsPer20"
                        },
                        new
                        {
                            Id = 50,
                            Name = "ReceivingYardsPer25"
                        },
                        new
                        {
                            Id = 51,
                            Name = "ReceivingYardsPer50"
                        },
                        new
                        {
                            Id = 52,
                            Name = "ReceivingYardsPer100"
                        },
                        new
                        {
                            Id = 53,
                            Name = "EachReception"
                        },
                        new
                        {
                            Id = 54,
                            Name = "ReceptionsPer5"
                        },
                        new
                        {
                            Id = 55,
                            Name = "ReceptionsPer10"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Receiving100To199YardGame"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Receiving200PlusYardGame"
                        },
                        new
                        {
                            Id = 58,
                            Name = "ReceivingTargets"
                        },
                        new
                        {
                            Id = 59,
                            Name = "ReceivingYardsAfterCatch"
                        },
                        new
                        {
                            Id = 60,
                            Name = "ReceivingYardsPerCatch"
                        },
                        new
                        {
                            Id = 61,
                            Name = "ReceivingYardsPerGame"
                        },
                        new
                        {
                            Id = 62,
                            Name = "TotalTwoPointConversions"
                        },
                        new
                        {
                            Id = 63,
                            Name = "FumbleRecoveredForTD"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Sacked"
                        },
                        new
                        {
                            Id = 65,
                            Name = "PassingFumbles"
                        },
                        new
                        {
                            Id = 66,
                            Name = "RushingFumbles"
                        },
                        new
                        {
                            Id = 67,
                            Name = "ReceivingFumbles"
                        },
                        new
                        {
                            Id = 68,
                            Name = "TotalFumbles"
                        },
                        new
                        {
                            Id = 69,
                            Name = "PassingFumblesLost"
                        },
                        new
                        {
                            Id = 70,
                            Name = "RushingFumblesLost"
                        },
                        new
                        {
                            Id = 71,
                            Name = "ReceivingFumblesLost"
                        },
                        new
                        {
                            Id = 72,
                            Name = "TotalFumblesLost"
                        },
                        new
                        {
                            Id = 73,
                            Name = "TotalTurnovers"
                        },
                        new
                        {
                            Id = 74,
                            Name = "FieldGoalMade50Plus"
                        },
                        new
                        {
                            Id = 75,
                            Name = "FieldGoalAttempted50Plus"
                        },
                        new
                        {
                            Id = 76,
                            Name = "FieldGoalMissed50Plus"
                        },
                        new
                        {
                            Id = 77,
                            Name = "FieldGoalMade40To49"
                        },
                        new
                        {
                            Id = 78,
                            Name = "FieldGoalAttempted40To49"
                        },
                        new
                        {
                            Id = 79,
                            Name = "FieldGoalMissed40To49"
                        },
                        new
                        {
                            Id = 80,
                            Name = "FieldGoalMade0To39"
                        },
                        new
                        {
                            Id = 81,
                            Name = "FieldGoalAttempted0To39"
                        },
                        new
                        {
                            Id = 82,
                            Name = "FieldGoalMissed0To39"
                        },
                        new
                        {
                            Id = 83,
                            Name = "TotalFieldGoalsMade"
                        },
                        new
                        {
                            Id = 84,
                            Name = "TotalFieldGoalsAttempted"
                        },
                        new
                        {
                            Id = 85,
                            Name = "TotalFieldGoalsMissed"
                        },
                        new
                        {
                            Id = 86,
                            Name = "PATMade"
                        },
                        new
                        {
                            Id = 87,
                            Name = "PATAttempted"
                        },
                        new
                        {
                            Id = 88,
                            Name = "PATMissed"
                        },
                        new
                        {
                            Id = 89,
                            Name = "PointsAllowed0"
                        },
                        new
                        {
                            Id = 90,
                            Name = "PointsAllowed1To6"
                        },
                        new
                        {
                            Id = 91,
                            Name = "PointsAllowed7To13"
                        },
                        new
                        {
                            Id = 92,
                            Name = "PointsAllowed14To17"
                        },
                        new
                        {
                            Id = 93,
                            Name = "BlockedKickReturnTD"
                        },
                        new
                        {
                            Id = 94,
                            Name = "FumbleOrIntReturnTD"
                        },
                        new
                        {
                            Id = 95,
                            Name = "DefenseInterception"
                        },
                        new
                        {
                            Id = 96,
                            Name = "DefenseFumbleRecovered"
                        },
                        new
                        {
                            Id = 97,
                            Name = "BlockedKick"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Safety"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Sack"
                        },
                        new
                        {
                            Id = 100,
                            Name = "HalfSack"
                        },
                        new
                        {
                            Id = 101,
                            Name = "KickoffReturnTD"
                        },
                        new
                        {
                            Id = 102,
                            Name = "PuntReturnTD"
                        },
                        new
                        {
                            Id = 103,
                            Name = "InterceptionReturnTD"
                        },
                        new
                        {
                            Id = 104,
                            Name = "FumbleReturnTD"
                        },
                        new
                        {
                            Id = 105,
                            Name = "TotalReturnTD"
                        },
                        new
                        {
                            Id = 106,
                            Name = "FumbleForced"
                        },
                        new
                        {
                            Id = 107,
                            Name = "AssistedTackles"
                        },
                        new
                        {
                            Id = 108,
                            Name = "SoloTackles"
                        },
                        new
                        {
                            Id = 109,
                            Name = "TotalTackles"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Every3Tackles"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Every5Tackles"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Stuffs"
                        },
                        new
                        {
                            Id = 113,
                            Name = "PassesDefended"
                        },
                        new
                        {
                            Id = 114,
                            Name = "KickoffReturnYards"
                        },
                        new
                        {
                            Id = 115,
                            Name = "PuntReturnYards"
                        },
                        new
                        {
                            Id = 116,
                            Name = "KickoffReturnYardsPer10"
                        },
                        new
                        {
                            Id = 117,
                            Name = "KickoffReturnYardsPer25"
                        },
                        new
                        {
                            Id = 118,
                            Name = "PuntReturnYardsPer10"
                        },
                        new
                        {
                            Id = 119,
                            Name = "PuntReturnYardsPer25"
                        },
                        new
                        {
                            Id = 120,
                            Name = "PointsAllowed"
                        },
                        new
                        {
                            Id = 121,
                            Name = "PointsAllowed18To21"
                        },
                        new
                        {
                            Id = 122,
                            Name = "PointsAllowed22To27"
                        },
                        new
                        {
                            Id = 123,
                            Name = "PointsAllowed28To34"
                        },
                        new
                        {
                            Id = 124,
                            Name = "PointsAllowed35To45"
                        },
                        new
                        {
                            Id = 125,
                            Name = "PointsAllowed46Plus"
                        },
                        new
                        {
                            Id = 126,
                            Name = "PointsAllowedPerGame"
                        },
                        new
                        {
                            Id = 127,
                            Name = "YardsAllowed"
                        },
                        new
                        {
                            Id = 128,
                            Name = "YardsAllowedLessThan100"
                        },
                        new
                        {
                            Id = 129,
                            Name = "YardsAllowed100To199"
                        },
                        new
                        {
                            Id = 130,
                            Name = "YardsAllowed200To299"
                        },
                        new
                        {
                            Id = 131,
                            Name = "YardsAllowed300To349"
                        },
                        new
                        {
                            Id = 132,
                            Name = "YardsAllowed350To399"
                        },
                        new
                        {
                            Id = 133,
                            Name = "YardsAllowed400To449"
                        },
                        new
                        {
                            Id = 134,
                            Name = "YardsAllowed450To499"
                        },
                        new
                        {
                            Id = 135,
                            Name = "YardsAllowed500To549"
                        },
                        new
                        {
                            Id = 136,
                            Name = "YardsAllowed550Plus"
                        },
                        new
                        {
                            Id = 137,
                            Name = "YardsAllowedPerGame"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Punts"
                        },
                        new
                        {
                            Id = 139,
                            Name = "PuntYards"
                        },
                        new
                        {
                            Id = 140,
                            Name = "PuntsInside10"
                        },
                        new
                        {
                            Id = 141,
                            Name = "PuntsInside20"
                        },
                        new
                        {
                            Id = 142,
                            Name = "BlockedPunts"
                        },
                        new
                        {
                            Id = 143,
                            Name = "PuntsReturned"
                        },
                        new
                        {
                            Id = 144,
                            Name = "PuntingReturnYards"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Touchbacks"
                        },
                        new
                        {
                            Id = 146,
                            Name = "FairCatches"
                        },
                        new
                        {
                            Id = 147,
                            Name = "PuntAverage"
                        },
                        new
                        {
                            Id = 148,
                            Name = "PuntAverage44Plus"
                        },
                        new
                        {
                            Id = 149,
                            Name = "PuntAverage42To43_9"
                        },
                        new
                        {
                            Id = 150,
                            Name = "PuntAverage40To41_9"
                        },
                        new
                        {
                            Id = 151,
                            Name = "PuntAverage38To39_9"
                        },
                        new
                        {
                            Id = 152,
                            Name = "PuntAverage36To37_9"
                        },
                        new
                        {
                            Id = 153,
                            Name = "PuntAverage34To35_9"
                        },
                        new
                        {
                            Id = 154,
                            Name = "PuntAverage33_9OrLess"
                        },
                        new
                        {
                            Id = 155,
                            Name = "TeamWin"
                        },
                        new
                        {
                            Id = 156,
                            Name = "TeamLoss"
                        },
                        new
                        {
                            Id = 157,
                            Name = "TeamTie"
                        },
                        new
                        {
                            Id = 158,
                            Name = "PointsScored"
                        },
                        new
                        {
                            Id = 159,
                            Name = "PointsPerGame"
                        },
                        new
                        {
                            Id = 160,
                            Name = "MarginOfVictory"
                        },
                        new
                        {
                            Id = 161,
                            Name = "WinMargin25Plus"
                        },
                        new
                        {
                            Id = 162,
                            Name = "WinMargin20To24"
                        },
                        new
                        {
                            Id = 163,
                            Name = "WinMargin15To19"
                        },
                        new
                        {
                            Id = 164,
                            Name = "WinMargin10To14"
                        },
                        new
                        {
                            Id = 165,
                            Name = "WinMargin5To9"
                        },
                        new
                        {
                            Id = 166,
                            Name = "WinMargin1To4"
                        },
                        new
                        {
                            Id = 167,
                            Name = "LossMargin1To4"
                        },
                        new
                        {
                            Id = 168,
                            Name = "LossMargin5To9"
                        },
                        new
                        {
                            Id = 169,
                            Name = "LossMargin10To14"
                        },
                        new
                        {
                            Id = 170,
                            Name = "LossMargin15To19"
                        },
                        new
                        {
                            Id = 171,
                            Name = "LossMargin20To24"
                        },
                        new
                        {
                            Id = 172,
                            Name = "LossMargin25Plus"
                        },
                        new
                        {
                            Id = 173,
                            Name = "MarginOfVictoryPerGame"
                        },
                        new
                        {
                            Id = 174,
                            Name = "WinningPercentage"
                        },
                        new
                        {
                            Id = 175,
                            Name = "PassingTD0To9Bonus"
                        },
                        new
                        {
                            Id = 176,
                            Name = "PassingTD10To19Bonus"
                        },
                        new
                        {
                            Id = 177,
                            Name = "PassingTD20To29Bonus"
                        },
                        new
                        {
                            Id = 178,
                            Name = "PassingTD30To39Bonus"
                        },
                        new
                        {
                            Id = 179,
                            Name = "RushingTD0To9Bonus"
                        },
                        new
                        {
                            Id = 180,
                            Name = "RushingTD10To19Bonus"
                        },
                        new
                        {
                            Id = 181,
                            Name = "RushingTD20To29Bonus"
                        },
                        new
                        {
                            Id = 182,
                            Name = "RushingTD30To39Bonus"
                        },
                        new
                        {
                            Id = 183,
                            Name = "ReceivingTD0To9Bonus"
                        },
                        new
                        {
                            Id = 184,
                            Name = "ReceivingTD10To19Bonus"
                        },
                        new
                        {
                            Id = 185,
                            Name = "ReceivingTD20To29Bonus"
                        },
                        new
                        {
                            Id = 186,
                            Name = "ReceivingTD30To39Bonus"
                        },
                        new
                        {
                            Id = 187,
                            Name = "DSTPointsAllowed"
                        },
                        new
                        {
                            Id = 188,
                            Name = "DSTPointsAllowed0"
                        },
                        new
                        {
                            Id = 189,
                            Name = "DSTPointsAllowed1To6"
                        },
                        new
                        {
                            Id = 190,
                            Name = "DSTPointsAllowed7To13"
                        },
                        new
                        {
                            Id = 191,
                            Name = "DSTPointsAllowed14To17"
                        },
                        new
                        {
                            Id = 192,
                            Name = "DSTPointsAllowed18To21"
                        },
                        new
                        {
                            Id = 193,
                            Name = "DSTPointsAllowed22To27"
                        },
                        new
                        {
                            Id = 194,
                            Name = "DSTPointsAllowed28To34"
                        },
                        new
                        {
                            Id = 195,
                            Name = "DSTPointsAllowed35To45"
                        },
                        new
                        {
                            Id = 196,
                            Name = "DSTPointsAllowed46Plus"
                        },
                        new
                        {
                            Id = 197,
                            Name = "DSTPointsAllowedPerGame"
                        },
                        new
                        {
                            Id = 198,
                            Name = "FieldGoalMade50To59"
                        },
                        new
                        {
                            Id = 199,
                            Name = "FieldGoalAttempted50To59"
                        },
                        new
                        {
                            Id = 200,
                            Name = "FieldGoalMissed50To59"
                        },
                        new
                        {
                            Id = 201,
                            Name = "FieldGoalMade60Plus"
                        },
                        new
                        {
                            Id = 202,
                            Name = "FieldGoalAttempted60Plus"
                        },
                        new
                        {
                            Id = 203,
                            Name = "FieldGoalMissed60Plus"
                        },
                        new
                        {
                            Id = 204,
                            Name = "OffensiveTwoPointReturn"
                        },
                        new
                        {
                            Id = 205,
                            Name = "DefensiveTwoPointReturn"
                        },
                        new
                        {
                            Id = 206,
                            Name = "TwoPointReturn"
                        },
                        new
                        {
                            Id = 207,
                            Name = "OffensiveOnePointSafety"
                        },
                        new
                        {
                            Id = 208,
                            Name = "DefensiveOnePointSafety"
                        },
                        new
                        {
                            Id = 209,
                            Name = "OnePointSafety"
                        },
                        new
                        {
                            Id = 210,
                            Name = "GamesPlayed"
                        },
                        new
                        {
                            Id = 211,
                            Name = "PassingFirstDown"
                        },
                        new
                        {
                            Id = 212,
                            Name = "RushingFirstDown"
                        },
                        new
                        {
                            Id = 213,
                            Name = "ReceivingFirstDown"
                        },
                        new
                        {
                            Id = 214,
                            Name = "FieldGoalMadeYards"
                        },
                        new
                        {
                            Id = 215,
                            Name = "FieldGoalMissedYards"
                        },
                        new
                        {
                            Id = 216,
                            Name = "FieldGoalAttemptYards"
                        },
                        new
                        {
                            Id = 217,
                            Name = "FieldGoalMadeYardsPer5"
                        },
                        new
                        {
                            Id = 218,
                            Name = "FieldGoalMadeYardsPer10"
                        },
                        new
                        {
                            Id = 219,
                            Name = "FieldGoalMadeYardsPer20"
                        },
                        new
                        {
                            Id = 220,
                            Name = "FieldGoalMadeYardsPer25"
                        },
                        new
                        {
                            Id = 221,
                            Name = "FieldGoalMadeYardsPer50"
                        },
                        new
                        {
                            Id = 222,
                            Name = "FieldGoalMadeYardsPer100"
                        },
                        new
                        {
                            Id = 223,
                            Name = "FieldGoalMissedYardsPer5"
                        },
                        new
                        {
                            Id = 224,
                            Name = "FieldGoalMissedYardsPer10"
                        },
                        new
                        {
                            Id = 225,
                            Name = "FieldGoalMissedYardsPer20"
                        },
                        new
                        {
                            Id = 226,
                            Name = "FieldGoalMissedYardsPer25"
                        },
                        new
                        {
                            Id = 227,
                            Name = "FieldGoalMissedYardsPer50"
                        },
                        new
                        {
                            Id = 228,
                            Name = "FieldGoalMissedYardsPer100"
                        },
                        new
                        {
                            Id = 229,
                            Name = "FieldGoalAttemptYardsPer5"
                        },
                        new
                        {
                            Id = 230,
                            Name = "FieldGoalAttemptYardsPer10"
                        },
                        new
                        {
                            Id = 231,
                            Name = "FieldGoalAttemptYardsPer20"
                        },
                        new
                        {
                            Id = 232,
                            Name = "FieldGoalAttemptYardsPer25"
                        },
                        new
                        {
                            Id = 233,
                            Name = "FieldGoalAttemptYardsPer50"
                        },
                        new
                        {
                            Id = 234,
                            Name = "FieldGoalAttemptYardsPer100"
                        });
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("ProviderTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_team_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamMatchup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("OpponentTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("opponent_team_id");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric")
                        .HasColumnName("score");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("Week")
                        .HasColumnType("integer")
                        .HasColumnName("week");

                    b.HasKey("Id")
                        .HasName("pk_team_matchups");

                    b.HasIndex("OpponentTeamId")
                        .HasDatabaseName("ix_team_matchups_opponent_team_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_matchups_team_id");

                    b.ToTable("team_matchups", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamSeasonStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<decimal>("PointsAgainst")
                        .HasColumnType("numeric")
                        .HasColumnName("points_against");

                    b.Property<decimal>("PointsFor")
                        .HasColumnType("numeric")
                        .HasColumnName("points_for");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("Ties")
                        .HasColumnType("integer")
                        .HasColumnName("ties");

                    b.Property<decimal>("WinPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("win_percentage");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id")
                        .HasName("pk_team_season_stats");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_season_stats_team_id");

                    b.ToTable("team_season_stats", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.AccumulatedStat", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.MatchupRosterSpot", null)
                        .WithMany("AccumulatedStats")
                        .HasForeignKey("MatchupRosterSpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accumulated_stats_matchup_roster_spots_matchup_roster_spot_");

                    b.HasOne("FantasyHOF.Domain.Types.Stat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accumulated_stats_stats_stat_id");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.FantasyMember", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.FantasyProvider", "FantasyProvider")
                        .WithMany()
                        .HasForeignKey("FantasyProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fantasy_members_fantasy_providers_fantasy_provider_id");

                    b.Navigation("FantasyProvider");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.League", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.FantasyProvider", "FantasyProvider")
                        .WithMany()
                        .HasForeignKey("FantasyProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leagues_fantasy_providers_fantasy_provider_id");

                    b.Navigation("FantasyProvider");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeason", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.League", null)
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_seasons_leagues_league_id");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMember", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeason", null)
                        .WithMany("LeagueSeasonMembers")
                        .HasForeignKey("LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_members_league_seasons_league_season_id");

                    b.HasOne("FantasyHOF.Domain.Types.FantasyMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_members_fantasy_members_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMemberTeam", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_member_teams_teams_team_id");

                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonMember", null)
                        .WithMany("LeagueSeasonMemberTeams")
                        .HasForeignKey("LeagueSeasonId", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_member_teams_league_season_members_league_sea");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScheduleSettings", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonSettings", null)
                        .WithOne("ScheduleSettings")
                        .HasForeignKey("FantasyHOF.Domain.Types.LeagueSeasonScheduleSettings", "LeagueSeasonId")
                        .HasPrincipalKey("FantasyHOF.Domain.Types.LeagueSeasonSettings", "LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_schedule_settings_league_season_settings_leag");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringItem", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", null)
                        .WithMany("ScoringItems")
                        .HasForeignKey("LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_scoring_items_league_season_scoring_settings_");

                    b.HasOne("FantasyHOF.Domain.Types.Stat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_scoring_items_stats_stat_id");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonSettings", null)
                        .WithOne("ScoringSettings")
                        .HasForeignKey("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", "LeagueSeasonId")
                        .HasPrincipalKey("FantasyHOF.Domain.Types.LeagueSeasonSettings", "LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_scoring_settings_league_season_settings_leagu");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonSettings", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeason", null)
                        .WithOne("Settings")
                        .HasForeignKey("FantasyHOF.Domain.Types.LeagueSeasonSettings", "LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_settings_league_seasons_league_season_id");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.MatchupRosterSpot", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.TeamMatchup", null)
                        .WithMany("MatchupRosterSpots")
                        .HasForeignKey("MatchupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matchup_roster_spots_team_matchups_matchup_id");

                    b.HasOne("FantasyHOF.Domain.Types.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matchup_roster_spots_players_player_id");

                    b.HasOne("FantasyHOF.Domain.Types.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matchup_roster_spots_positions_position_id");

                    b.Navigation("Player");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Player", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.FantasyProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_players_fantasy_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamMatchup", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.Team", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_team_matchups_teams_opponent_team_id");

                    b.HasOne("FantasyHOF.Domain.Types.Team", null)
                        .WithMany("Matchups")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_matchups_teams_team_id");

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamSeasonStats", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.Team", null)
                        .WithOne("SeasonStats")
                        .HasForeignKey("FantasyHOF.Domain.Types.TeamSeasonStats", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_season_stats_teams_team_id");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.League", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeason", b =>
                {
                    b.Navigation("LeagueSeasonMembers");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMember", b =>
                {
                    b.Navigation("LeagueSeasonMemberTeams");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", b =>
                {
                    b.Navigation("ScoringItems");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonSettings", b =>
                {
                    b.Navigation("ScheduleSettings")
                        .IsRequired();

                    b.Navigation("ScoringSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.MatchupRosterSpot", b =>
                {
                    b.Navigation("AccumulatedStats");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Team", b =>
                {
                    b.Navigation("Matchups");

                    b.Navigation("SeasonStats")
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamMatchup", b =>
                {
                    b.Navigation("MatchupRosterSpots");
                });
#pragma warning restore 612, 618
        }
    }
}
