// <auto-generated />
using FantasyHOF.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyHOF.EntityFramework.Migrations
{
    [DbContext(typeof(FantasyHOFDBContext))]
    [Migration("20251218202550_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyHOF.Domain.Types.AccumulatedStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchupRosterSpotId")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_roster_spot_id");

                    b.Property<decimal>("PointsScored")
                        .HasColumnType("numeric")
                        .HasColumnName("points_scored");

                    b.Property<int>("StatId")
                        .HasColumnType("integer")
                        .HasColumnName("stat_id");

                    b.Property<decimal>("StatValue")
                        .HasColumnType("numeric")
                        .HasColumnName("stat_value");

                    b.HasKey("Id")
                        .HasName("pk_accumulated_stats");

                    b.HasIndex("MatchupRosterSpotId")
                        .HasDatabaseName("ix_accumulated_stats_matchup_roster_spot_id");

                    b.HasIndex("StatId")
                        .HasDatabaseName("ix_accumulated_stats_stat_id");

                    b.ToTable("accumulated_stats", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.FantasyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("FantasyProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("fantasy_provider_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("ProviderMemberId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_member_id");

                    b.HasKey("Id")
                        .HasName("pk_fantasy_members");

                    b.HasIndex("FantasyProviderId", "ProviderMemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_fantasy_members_fantasy_provider_id_provider_member_id");

                    b.ToTable("fantasy_members", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.FantasyProvider", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fantasy_providers");

                    b.ToTable("fantasy_providers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ESPN"
                        });
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FantasyProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("fantasy_provider_id");

                    b.Property<string>("ProviderLeagueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_league_id");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.HasKey("Id")
                        .HasName("pk_leagues");

                    b.HasIndex("FantasyProviderId")
                        .HasDatabaseName("ix_leagues_fantasy_provider_id");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_league_seasons");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_league_seasons_league_id");

                    b.ToTable("league_seasons", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMember", b =>
                {
                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<bool>("IsLeagueCreator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_league_creator");

                    b.Property<bool>("IsLeagueManager")
                        .HasColumnType("boolean")
                        .HasColumnName("is_league_manager");

                    b.HasKey("LeagueSeasonId", "MemberId")
                        .HasName("pk_league_season_members");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_league_season_members_member_id");

                    b.ToTable("league_season_members", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMemberTeam", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.HasKey("MemberId", "TeamId")
                        .HasName("pk_league_season_member_teams");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_league_season_member_teams_team_id");

                    b.HasIndex("LeagueSeasonId", "MemberId")
                        .HasDatabaseName("ix_league_season_member_teams_league_season_id_member_id");

                    b.ToTable("league_season_member_teams", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScheduleSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<int>("MatchupCount")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_count");

                    b.Property<int>("MatchupLength")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_length");

                    b.Property<int>("PlayoffMatchupLength")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_matchup_length");

                    b.Property<int>("PlayoffTeamCount")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_team_count");

                    b.Property<bool>("VariablePlayoffMatchupLength")
                        .HasColumnType("boolean")
                        .HasColumnName("variable_playoff_matchup_length");

                    b.HasKey("Id")
                        .HasName("pk_league_season_schedule_settings");

                    b.HasIndex("LeagueSeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_season_schedule_settings_league_season_id");

                    b.ToTable("league_season_schedule_settings", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric")
                        .HasColumnName("points");

                    b.Property<int>("StatId")
                        .HasColumnType("integer")
                        .HasColumnName("stat_id");

                    b.HasKey("Id")
                        .HasName("pk_league_season_scoring_items");

                    b.HasIndex("LeagueSeasonId")
                        .HasDatabaseName("ix_league_season_scoring_items_league_season_id");

                    b.HasIndex("StatId")
                        .HasDatabaseName("ix_league_season_scoring_items_stat_id");

                    b.ToTable("league_season_scoring_items", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HomeTeamBonusPoints")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_bonus_points");

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<string>("MatchupTieRule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matchup_tie_rule");

                    b.Property<int>("MatchupTieRuleBy")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_tie_rule_by");

                    b.Property<string>("PlayerRankType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_rank_type");

                    b.Property<int>("PlayoffHomeTeamBonusPoints")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_home_team_bonus_points");

                    b.Property<string>("PlayoffMatchupTieRule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("playoff_matchup_tie_rule");

                    b.Property<int>("PlayoffMatchupTieRuleBy")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_matchup_tie_rule_by");

                    b.Property<string>("ScoringType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scoring_type");

                    b.HasKey("Id")
                        .HasName("pk_league_season_scoring_settings");

                    b.HasIndex("LeagueSeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_season_scoring_settings_league_season_id");

                    b.ToTable("league_season_scoring_settings", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("league_name");

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.HasKey("Id")
                        .HasName("pk_league_season_settings");

                    b.HasAlternateKey("LeagueSeasonId")
                        .HasName("ak_league_season_settings_league_season_id");

                    b.ToTable("league_season_settings", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.MatchupOutcome", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_matchup_outcomes");

                    b.ToTable("matchup_outcomes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Win"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Loss"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Undecided"
                        },
                        new
                        {
                            Id = 999,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.MatchupRosterSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchupId")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<decimal>("PointsScored")
                        .HasColumnType("numeric")
                        .HasColumnName("points_scored");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.HasKey("Id")
                        .HasName("pk_matchup_roster_spots");

                    b.HasIndex("MatchupId")
                        .HasDatabaseName("ix_matchup_roster_spots_matchup_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_matchup_roster_spots_player_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_matchup_roster_spots_position_id");

                    b.ToTable("matchup_roster_spots", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.MatchupType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_matchup_types");

                    b.ToTable("matchup_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Regular season"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Losers bracket"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Winners consolation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Winners bracket"
                        },
                        new
                        {
                            Id = 999,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<int>("ProviderPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_player_id");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("ProviderId", "ProviderPlayerId")
                        .HasDatabaseName("ix_players_provider_id_provider_player_id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Position", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.ToTable("positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "QB"
                        },
                        new
                        {
                            Id = 1,
                            Name = "TQB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "RB"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RBWR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "WR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "WRTE"
                        },
                        new
                        {
                            Id = 6,
                            Name = "TE"
                        },
                        new
                        {
                            Id = 7,
                            Name = "OP"
                        },
                        new
                        {
                            Id = 8,
                            Name = "DT"
                        },
                        new
                        {
                            Id = 9,
                            Name = "DE"
                        },
                        new
                        {
                            Id = 10,
                            Name = "LB"
                        },
                        new
                        {
                            Id = 11,
                            Name = "DL"
                        },
                        new
                        {
                            Id = 12,
                            Name = "CB"
                        },
                        new
                        {
                            Id = 13,
                            Name = "S"
                        },
                        new
                        {
                            Id = 14,
                            Name = "DB"
                        },
                        new
                        {
                            Id = 15,
                            Name = "DP"
                        },
                        new
                        {
                            Id = 16,
                            Name = "DST"
                        },
                        new
                        {
                            Id = 17,
                            Name = "K"
                        },
                        new
                        {
                            Id = 18,
                            Name = "P"
                        },
                        new
                        {
                            Id = 19,
                            Name = "HC"
                        },
                        new
                        {
                            Id = 20,
                            Name = "BE"
                        },
                        new
                        {
                            Id = 21,
                            Name = "IR"
                        },
                        new
                        {
                            Id = 23,
                            Name = "RBWRTE"
                        },
                        new
                        {
                            Id = 24,
                            Name = "ER"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Rookie"
                        },
                        new
                        {
                            Id = 999,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Stat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_stats");

                    b.ToTable("stats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Attempted passes"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Completed passes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Incomplete passes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Passing yards"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Passing touchdowns"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Passing yards (per 5)"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Passing yards (per 10)"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Passing yards (per 20)"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Passing yards (per 25)"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Passing yards (per 50)"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Passing yards (per 100)"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pass completions (per 5)"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pass completions (per 10)"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pass incompletions (per 5)"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pass incompletions (per 10)"
                        },
                        new
                        {
                            Id = 15,
                            Name = "40+ yard passing TD bonus"
                        },
                        new
                        {
                            Id = 16,
                            Name = "50+ yard passing TD bonus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "300–399 passing yard game"
                        },
                        new
                        {
                            Id = 18,
                            Name = "400+ passing yard game"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Passing two-point conversion"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Interceptions thrown"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Completion percentage"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Passing yards per game"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Rushing attempts"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Rushing yards"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Rushing touchdowns"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Rushing two-point conversion"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Rushing yards (per 5)"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Rushing yards (per 10)"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Rushing yards (per 20)"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Rushing yards (per 25)"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Rushing yards (per 50)"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Rushing yards (per 100)"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Rushing attempts (per 5)"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Rushing attempts (per 10)"
                        },
                        new
                        {
                            Id = 35,
                            Name = "40+ yard rushing TD bonus"
                        },
                        new
                        {
                            Id = 36,
                            Name = "50+ yard rushing TD bonus"
                        },
                        new
                        {
                            Id = 37,
                            Name = "100–199 rushing yard game"
                        },
                        new
                        {
                            Id = 38,
                            Name = "200+ rushing yard game"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Rushing yards per attempt"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Rushing yards per game"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Receptions"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Receiving yards"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Receiving touchdowns"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Receiving two-point conversion"
                        },
                        new
                        {
                            Id = 45,
                            Name = "40+ yard receiving TD bonus"
                        },
                        new
                        {
                            Id = 46,
                            Name = "50+ yard receiving TD bonus"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Receiving yards (per 5)"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Receiving yards (per 10)"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Receiving yards (per 20)"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Receiving yards (per 25)"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Receiving yards (per 50)"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Receiving yards (per 100)"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Each reception"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Receptions (per 5)"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Receptions (per 10)"
                        },
                        new
                        {
                            Id = 56,
                            Name = "100–199 receiving yard game"
                        },
                        new
                        {
                            Id = 57,
                            Name = "200+ receiving yard game"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Receiving targets"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Yards after catch"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Yards per reception"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Receiving yards per game"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Total two-point conversions"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Fumble recovered for touchdown"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Times sacked"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Passing fumbles"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Rushing fumbles"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Receiving fumbles"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Total fumbles"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Passing fumbles lost"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Rushing fumbles lost"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Receiving fumbles lost"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Total fumbles lost"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Total turnovers"
                        },
                        new
                        {
                            Id = 74,
                            Name = "50+ yard field goals made"
                        },
                        new
                        {
                            Id = 75,
                            Name = "50+ yard field goals attempted"
                        },
                        new
                        {
                            Id = 76,
                            Name = "50+ yard field goals missed"
                        },
                        new
                        {
                            Id = 77,
                            Name = "40–49 yard field goals made"
                        },
                        new
                        {
                            Id = 78,
                            Name = "40–49 yard field goals attempted"
                        },
                        new
                        {
                            Id = 79,
                            Name = "40–49 yard field goals missed"
                        },
                        new
                        {
                            Id = 80,
                            Name = "0–39 yard field goals made"
                        },
                        new
                        {
                            Id = 81,
                            Name = "0–39 yard field goals attempted"
                        },
                        new
                        {
                            Id = 82,
                            Name = "0–39 yard field goals missed"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Total field goals made"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Total field goals attempted"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Total field goals missed"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Extra points made"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Extra points attempted"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Extra points missed"
                        },
                        new
                        {
                            Id = 89,
                            Name = "0 points allowed"
                        },
                        new
                        {
                            Id = 90,
                            Name = "1–6 points allowed"
                        },
                        new
                        {
                            Id = 91,
                            Name = "7–13 points allowed"
                        },
                        new
                        {
                            Id = 92,
                            Name = "14–17 points allowed"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Blocked kick returned for TD"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Fumble or interception return TD"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Defensive interception"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Defensive fumble recovered"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Blocked kick"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Safety"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Sack"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Half sack"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Kickoff return TD"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Punt return TD"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Interception return TD"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Fumble return TD"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Total return TDs"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Fumbles forced"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Assisted tackles"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Solo tackles"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Total tackles"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Every 3 tackles"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Every 5 tackles"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Stuffs (tackles for loss)"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Passes defended"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Kickoff return yards"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Punt return yards"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Kickoff return yards (per 10)"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Kickoff return yards (per 25)"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Punt return yards (per 10)"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Punt return yards (per 25)"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Points allowed"
                        },
                        new
                        {
                            Id = 121,
                            Name = "18–21 points allowed"
                        },
                        new
                        {
                            Id = 122,
                            Name = "22–27 points allowed"
                        },
                        new
                        {
                            Id = 123,
                            Name = "28–34 points allowed"
                        },
                        new
                        {
                            Id = 124,
                            Name = "35–45 points allowed"
                        },
                        new
                        {
                            Id = 125,
                            Name = "46+ points allowed"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Points allowed per game"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Yards allowed"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Under 100 yards allowed"
                        },
                        new
                        {
                            Id = 129,
                            Name = "100–199 yards allowed"
                        },
                        new
                        {
                            Id = 130,
                            Name = "200–299 yards allowed"
                        },
                        new
                        {
                            Id = 131,
                            Name = "300–349 yards allowed"
                        },
                        new
                        {
                            Id = 132,
                            Name = "350–399 yards allowed"
                        },
                        new
                        {
                            Id = 133,
                            Name = "400–449 yards allowed"
                        },
                        new
                        {
                            Id = 134,
                            Name = "450–499 yards allowed"
                        },
                        new
                        {
                            Id = 135,
                            Name = "500–549 yards allowed"
                        },
                        new
                        {
                            Id = 136,
                            Name = "550+ yards allowed"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Yards allowed per game"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Punts"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Punt yards"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Punts inside the 10"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Punts inside the 20"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Blocked punts"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Punts returned"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Punt return yards allowed"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Touchbacks"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Fair catches"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Punt average"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Punt average (44+ yards)"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Punt average (42–43.9 yards)"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Punt average (40–41.9 yards)"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Punt average (38–39.9 yards)"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Punt average (36–37.9 yards)"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Punt average (34–35.9 yards)"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Punt average (33.9 yards or less)"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Team win"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Team loss"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Team tie"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Points scored"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Points per game"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Margin of victory"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Win margin 25+"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Win margin 20–24"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Win margin 15–19"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Win margin 10–14"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Win margin 5–9"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Win margin 1–4"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Loss margin 1–4"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Loss margin 5–9"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Loss margin 10–14"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Loss margin 15–19"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Loss margin 20–24"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Loss margin 25+"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Margin of victory per game"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Winning percentage"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Passing TD bonus (0–9 yards)"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Passing TD bonus (10–19 yards)"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Passing TD bonus (20–29 yards)"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Passing TD bonus (30–39 yards)"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Rushing TD bonus (0–9 yards)"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Rushing TD bonus (10–19 yards)"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Rushing TD bonus (20–29 yards)"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Rushing TD bonus (30–39 yards)"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Receiving TD bonus (0–9 yards)"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Receiving TD bonus (10–19 yards)"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Receiving TD bonus (20–29 yards)"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Receiving TD bonus (30–39 yards)"
                        },
                        new
                        {
                            Id = 187,
                            Name = "D/ST points allowed"
                        },
                        new
                        {
                            Id = 188,
                            Name = "D/ST 0 points allowed"
                        },
                        new
                        {
                            Id = 189,
                            Name = "D/ST 1–6 points allowed"
                        },
                        new
                        {
                            Id = 190,
                            Name = "D/ST 7–13 points allowed"
                        },
                        new
                        {
                            Id = 191,
                            Name = "D/ST 14–17 points allowed"
                        },
                        new
                        {
                            Id = 192,
                            Name = "D/ST 18–21 points allowed"
                        },
                        new
                        {
                            Id = 193,
                            Name = "D/ST 22–27 points allowed"
                        },
                        new
                        {
                            Id = 194,
                            Name = "D/ST 28–34 points allowed"
                        },
                        new
                        {
                            Id = 195,
                            Name = "D/ST 35–45 points allowed"
                        },
                        new
                        {
                            Id = 196,
                            Name = "D/ST 46+ points allowed"
                        },
                        new
                        {
                            Id = 197,
                            Name = "D/ST points allowed per game"
                        },
                        new
                        {
                            Id = 198,
                            Name = "50–59 yard field goals made"
                        },
                        new
                        {
                            Id = 199,
                            Name = "50–59 yard field goals attempted"
                        },
                        new
                        {
                            Id = 200,
                            Name = "50–59 yard field goals missed"
                        },
                        new
                        {
                            Id = 201,
                            Name = "60+ yard field goals made"
                        },
                        new
                        {
                            Id = 202,
                            Name = "60+ yard field goals attempted"
                        },
                        new
                        {
                            Id = 203,
                            Name = "60+ yard field goals missed"
                        },
                        new
                        {
                            Id = 204,
                            Name = "Offensive two-point return"
                        },
                        new
                        {
                            Id = 205,
                            Name = "Defensive two-point return"
                        },
                        new
                        {
                            Id = 206,
                            Name = "Two-point return"
                        },
                        new
                        {
                            Id = 207,
                            Name = "Offensive one-point safety"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Defensive one-point safety"
                        },
                        new
                        {
                            Id = 209,
                            Name = "One-point safety"
                        },
                        new
                        {
                            Id = 210,
                            Name = "Games played"
                        },
                        new
                        {
                            Id = 211,
                            Name = "Passing first downs"
                        },
                        new
                        {
                            Id = 212,
                            Name = "Rushing first downs"
                        },
                        new
                        {
                            Id = 213,
                            Name = "Receiving first downs"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Field goal made yards"
                        },
                        new
                        {
                            Id = 215,
                            Name = "Field goal missed yards"
                        },
                        new
                        {
                            Id = 216,
                            Name = "Field goal attempt yards"
                        },
                        new
                        {
                            Id = 217,
                            Name = "Field goal made yards (per 5)"
                        },
                        new
                        {
                            Id = 218,
                            Name = "Field goal made yards (per 10)"
                        },
                        new
                        {
                            Id = 219,
                            Name = "Field goal made yards (per 20)"
                        },
                        new
                        {
                            Id = 220,
                            Name = "Field goal made yards (per 25)"
                        },
                        new
                        {
                            Id = 221,
                            Name = "Field goal made yards (per 50)"
                        },
                        new
                        {
                            Id = 222,
                            Name = "Field goal made yards (per 100)"
                        },
                        new
                        {
                            Id = 223,
                            Name = "Field goal missed yards (per 5)"
                        },
                        new
                        {
                            Id = 224,
                            Name = "Field goal missed yards (per 10)"
                        },
                        new
                        {
                            Id = 225,
                            Name = "Field goal missed yards (per 20)"
                        },
                        new
                        {
                            Id = 226,
                            Name = "Field goal missed yards (per 25)"
                        },
                        new
                        {
                            Id = 227,
                            Name = "Field goal missed yards (per 50)"
                        },
                        new
                        {
                            Id = 228,
                            Name = "Field goal missed yards (per 100)"
                        },
                        new
                        {
                            Id = 229,
                            Name = "Field goal attempt yards (per 5)"
                        },
                        new
                        {
                            Id = 230,
                            Name = "Field goal attempt yards (per 10)"
                        },
                        new
                        {
                            Id = 231,
                            Name = "Field goal attempt yards (per 20)"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Field goal attempt yards (per 25)"
                        },
                        new
                        {
                            Id = 233,
                            Name = "Field goal attempt yards (per 50)"
                        },
                        new
                        {
                            Id = 234,
                            Name = "Field goal attempt yards (per 100)"
                        });
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("LogoURL")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("ProviderTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_team_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamMatchup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchupOutcomeId")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_outcome_id");

                    b.Property<int>("MatchupTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_type_id");

                    b.Property<int?>("OpponentTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("opponent_team_id");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric")
                        .HasColumnName("score");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("Week")
                        .HasColumnType("integer")
                        .HasColumnName("week");

                    b.HasKey("Id")
                        .HasName("pk_team_matchups");

                    b.HasIndex("MatchupOutcomeId")
                        .HasDatabaseName("ix_team_matchups_matchup_outcome_id");

                    b.HasIndex("MatchupTypeId")
                        .HasDatabaseName("ix_team_matchups_matchup_type_id");

                    b.HasIndex("OpponentTeamId")
                        .HasDatabaseName("ix_team_matchups_opponent_team_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_matchups_team_id");

                    b.ToTable("team_matchups", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamSeasonStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<decimal>("PointsAgainst")
                        .HasColumnType("numeric")
                        .HasColumnName("points_against");

                    b.Property<decimal>("PointsFor")
                        .HasColumnType("numeric")
                        .HasColumnName("points_for");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("Ties")
                        .HasColumnType("integer")
                        .HasColumnName("ties");

                    b.Property<decimal>("WinPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("win_percentage");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id")
                        .HasName("pk_team_season_stats");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_season_stats_team_id");

                    b.ToTable("team_season_stats", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.AccumulatedStat", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.MatchupRosterSpot", null)
                        .WithMany("AccumulatedStats")
                        .HasForeignKey("MatchupRosterSpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accumulated_stats_matchup_roster_spots_matchup_roster_spot_");

                    b.HasOne("FantasyHOF.Domain.Types.Stat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accumulated_stats_stats_stat_id");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.FantasyMember", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.FantasyProvider", "FantasyProvider")
                        .WithMany()
                        .HasForeignKey("FantasyProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fantasy_members_fantasy_providers_fantasy_provider_id");

                    b.Navigation("FantasyProvider");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.League", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.FantasyProvider", "FantasyProvider")
                        .WithMany()
                        .HasForeignKey("FantasyProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leagues_fantasy_providers_fantasy_provider_id");

                    b.Navigation("FantasyProvider");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeason", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.League", null)
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_seasons_leagues_league_id");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMember", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeason", null)
                        .WithMany("LeagueSeasonMembers")
                        .HasForeignKey("LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_members_league_seasons_league_season_id");

                    b.HasOne("FantasyHOF.Domain.Types.FantasyMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_members_fantasy_members_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMemberTeam", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_member_teams_teams_team_id");

                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonMember", null)
                        .WithMany("LeagueSeasonMemberTeams")
                        .HasForeignKey("LeagueSeasonId", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_member_teams_league_season_members_league_sea");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScheduleSettings", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonSettings", null)
                        .WithOne("ScheduleSettings")
                        .HasForeignKey("FantasyHOF.Domain.Types.LeagueSeasonScheduleSettings", "LeagueSeasonId")
                        .HasPrincipalKey("FantasyHOF.Domain.Types.LeagueSeasonSettings", "LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_schedule_settings_league_season_settings_leag");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringItem", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", null)
                        .WithMany("ScoringItems")
                        .HasForeignKey("LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_scoring_items_league_season_scoring_settings_");

                    b.HasOne("FantasyHOF.Domain.Types.Stat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_scoring_items_stats_stat_id");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonSettings", null)
                        .WithOne("ScoringSettings")
                        .HasForeignKey("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", "LeagueSeasonId")
                        .HasPrincipalKey("FantasyHOF.Domain.Types.LeagueSeasonSettings", "LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_scoring_settings_league_season_settings_leagu");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonSettings", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeason", null)
                        .WithOne("Settings")
                        .HasForeignKey("FantasyHOF.Domain.Types.LeagueSeasonSettings", "LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_settings_league_seasons_league_season_id");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.MatchupRosterSpot", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.TeamMatchup", null)
                        .WithMany("MatchupRosterSpots")
                        .HasForeignKey("MatchupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matchup_roster_spots_team_matchups_matchup_id");

                    b.HasOne("FantasyHOF.Domain.Types.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matchup_roster_spots_players_player_id");

                    b.HasOne("FantasyHOF.Domain.Types.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matchup_roster_spots_positions_position_id");

                    b.Navigation("Player");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Player", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.FantasyProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_players_fantasy_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamMatchup", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.MatchupOutcome", "MatchupOutcome")
                        .WithMany()
                        .HasForeignKey("MatchupOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_matchups_matchup_outcomes_matchup_outcome_id");

                    b.HasOne("FantasyHOF.Domain.Types.MatchupType", "MatchupType")
                        .WithMany()
                        .HasForeignKey("MatchupTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_matchups_matchup_types_matchup_type_id");

                    b.HasOne("FantasyHOF.Domain.Types.Team", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_team_matchups_teams_opponent_team_id");

                    b.HasOne("FantasyHOF.Domain.Types.Team", null)
                        .WithMany("Matchups")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_matchups_teams_team_id");

                    b.Navigation("MatchupOutcome");

                    b.Navigation("MatchupType");

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamSeasonStats", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.Team", null)
                        .WithOne("SeasonStats")
                        .HasForeignKey("FantasyHOF.Domain.Types.TeamSeasonStats", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_season_stats_teams_team_id");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.League", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeason", b =>
                {
                    b.Navigation("LeagueSeasonMembers");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMember", b =>
                {
                    b.Navigation("LeagueSeasonMemberTeams");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", b =>
                {
                    b.Navigation("ScoringItems");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonSettings", b =>
                {
                    b.Navigation("ScheduleSettings")
                        .IsRequired();

                    b.Navigation("ScoringSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.MatchupRosterSpot", b =>
                {
                    b.Navigation("AccumulatedStats");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Team", b =>
                {
                    b.Navigation("Matchups");

                    b.Navigation("SeasonStats")
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamMatchup", b =>
                {
                    b.Navigation("MatchupRosterSpots");
                });
#pragma warning restore 612, 618
        }
    }
}
