// <auto-generated />
using FantasyHOF.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyHOF.EntityFramework.Migrations
{
    [DbContext(typeof(FantasyHOFDBContext))]
    [Migration("20251212194447_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyHOF.Domain.Types.AccumulatedStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchupRosterSpotId")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_roster_spot_id");

                    b.Property<float>("PointsScored")
                        .HasColumnType("real")
                        .HasColumnName("points_scored");

                    b.Property<int>("StatId")
                        .HasColumnType("integer")
                        .HasColumnName("stat_id");

                    b.Property<float>("StatValue")
                        .HasColumnType("real")
                        .HasColumnName("stat_value");

                    b.HasKey("Id")
                        .HasName("pk_accumulated_stats");

                    b.HasIndex("MatchupRosterSpotId")
                        .HasDatabaseName("ix_accumulated_stats_matchup_roster_spot_id");

                    b.HasIndex("StatId")
                        .HasDatabaseName("ix_accumulated_stats_stat_id");

                    b.ToTable("accumulated_stats", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.FantasyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("ProviderMemberId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_member_id");

                    b.HasKey("Id")
                        .HasName("pk_fantasy_members");

                    b.ToTable("fantasy_members", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.FantasyProvider", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fantasy_providers");

                    b.ToTable("fantasy_providers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ESPN"
                        });
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FantasyProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("fantasy_provider_id");

                    b.Property<string>("ProviderLeagueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_league_id");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.HasKey("Id")
                        .HasName("pk_leagues");

                    b.HasIndex("FantasyProviderId")
                        .HasDatabaseName("ix_leagues_fantasy_provider_id");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_league_seasons");

                    b.ToTable("league_seasons", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMember", b =>
                {
                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<bool>("IsLeagueCreator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_league_creator");

                    b.Property<bool>("IsLeagueManager")
                        .HasColumnType("boolean")
                        .HasColumnName("is_league_manager");

                    b.HasKey("LeagueSeasonId", "MemberId")
                        .HasName("pk_league_season_members");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_league_season_members_member_id");

                    b.ToTable("league_season_members", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMemberTeam", b =>
                {
                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("LeagueSeasonId", "MemberId", "TeamId")
                        .HasName("pk_league_season_member_teams");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_league_season_member_teams_team_id");

                    b.ToTable("league_season_member_teams", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScheduleSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<int>("MatchupCount")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_count");

                    b.Property<int>("MatchupLength")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_length");

                    b.Property<int>("PlayoffMatchupLength")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_matchup_length");

                    b.Property<int>("PlayoffTeamCount")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_team_count");

                    b.Property<bool>("VariablePlayoffMatchupLength")
                        .HasColumnType("boolean")
                        .HasColumnName("variable_playoff_matchup_length");

                    b.HasKey("Id")
                        .HasName("pk_league_season_schedule_settings");

                    b.HasIndex("LeagueSeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_season_schedule_settings_league_season_id");

                    b.ToTable("league_season_schedule_settings", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<float>("Points")
                        .HasColumnType("real")
                        .HasColumnName("points");

                    b.Property<int>("StatId")
                        .HasColumnType("integer")
                        .HasColumnName("stat_id");

                    b.HasKey("Id")
                        .HasName("pk_league_season_scoring_items");

                    b.HasIndex("LeagueSeasonId")
                        .HasDatabaseName("ix_league_season_scoring_items_league_season_id");

                    b.HasIndex("StatId")
                        .HasDatabaseName("ix_league_season_scoring_items_stat_id");

                    b.ToTable("league_season_scoring_items", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HomeTeamBonusPoints")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_bonus_points");

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<string>("MatchupTieRule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matchup_tie_rule");

                    b.Property<int>("MatchupTieRuleBy")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_tie_rule_by");

                    b.Property<string>("PlayerRankType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_rank_type");

                    b.Property<int>("PlayoffHomeTeamBonusPoints")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_home_team_bonus_points");

                    b.Property<string>("PlayoffMatchupTieRule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("playoff_matchup_tie_rule");

                    b.Property<int>("PlayoffMatchupTieRuleBy")
                        .HasColumnType("integer")
                        .HasColumnName("playoff_matchup_tie_rule_by");

                    b.Property<string>("ScoringType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scoring_type");

                    b.HasKey("Id")
                        .HasName("pk_league_season_scoring_settings");

                    b.HasIndex("LeagueSeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_season_scoring_settings_league_season_id");

                    b.ToTable("league_season_scoring_settings", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("league_name");

                    b.Property<int>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.HasKey("Id")
                        .HasName("pk_league_season_settings");

                    b.HasIndex("LeagueSeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_season_settings_league_season_id");

                    b.ToTable("league_season_settings", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.MatchupRosterSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchupId")
                        .HasColumnType("integer")
                        .HasColumnName("matchup_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<float>("PointsScored")
                        .HasColumnType("real")
                        .HasColumnName("points_scored");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.HasKey("Id")
                        .HasName("pk_matchup_roster_spots");

                    b.HasIndex("MatchupId")
                        .HasDatabaseName("ix_matchup_roster_spots_matchup_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_matchup_roster_spots_player_id");

                    b.ToTable("matchup_roster_spots", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<int>("ProviderPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_player_id");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_players_provider_id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Stat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_stats");

                    b.ToTable("stats", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("ProviderTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_team_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamMatchup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LeagueSeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("league_season_id");

                    b.Property<int>("OpponentId")
                        .HasColumnType("integer")
                        .HasColumnName("opponent_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("Week")
                        .HasColumnType("integer")
                        .HasColumnName("week");

                    b.HasKey("Id")
                        .HasName("pk_team_matchups");

                    b.HasIndex("LeagueSeasonId")
                        .HasDatabaseName("ix_team_matchups_league_season_id");

                    b.HasIndex("OpponentId")
                        .HasDatabaseName("ix_team_matchups_opponent_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_team_matchups_team_id");

                    b.ToTable("team_matchups", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamSeasonStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<float>("PointsAgainst")
                        .HasColumnType("real")
                        .HasColumnName("points_against");

                    b.Property<float>("PointsFor")
                        .HasColumnType("real")
                        .HasColumnName("points_for");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("Ties")
                        .HasColumnType("integer")
                        .HasColumnName("ties");

                    b.Property<double>("WinPercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("win_percentage");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id")
                        .HasName("pk_team_season_stats");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_season_stats_team_id");

                    b.ToTable("team_season_stats", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.AccumulatedStat", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.MatchupRosterSpot", null)
                        .WithMany("AccumulatedStats")
                        .HasForeignKey("MatchupRosterSpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accumulated_stats_matchup_roster_spots_matchup_roster_spot_");

                    b.HasOne("FantasyHOF.Domain.Types.Stat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accumulated_stats_stats_stat_id");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.League", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.FantasyProvider", "FantasyProvider")
                        .WithMany()
                        .HasForeignKey("FantasyProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leagues_fantasy_providers_fantasy_provider_id");

                    b.Navigation("FantasyProvider");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMember", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeason", null)
                        .WithMany("LeagueSeasonMembers")
                        .HasForeignKey("LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_members_league_seasons_league_season_id");

                    b.HasOne("FantasyHOF.Domain.Types.FantasyMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_members_fantasy_members_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMemberTeam", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_member_teams_teams_team_id");

                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonMember", null)
                        .WithMany("LeagueSeasonMemberTeams")
                        .HasForeignKey("LeagueSeasonId", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_member_teams_league_season_members_league_sea");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScheduleSettings", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonSettings", null)
                        .WithOne("ScheduleSettings")
                        .HasForeignKey("FantasyHOF.Domain.Types.LeagueSeasonScheduleSettings", "LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_schedule_settings_league_season_settings_leag");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringItem", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", null)
                        .WithMany("ScoringItems")
                        .HasForeignKey("LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_scoring_items_league_season_scoring_settings_");

                    b.HasOne("FantasyHOF.Domain.Types.Stat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_scoring_items_stats_stat_id");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeasonSettings", null)
                        .WithOne("ScoringSettings")
                        .HasForeignKey("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", "LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_scoring_settings_league_season_settings_leagu");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonSettings", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeason", null)
                        .WithOne("Settings")
                        .HasForeignKey("FantasyHOF.Domain.Types.LeagueSeasonSettings", "LeagueSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_season_settings_league_seasons_league_season_id");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.MatchupRosterSpot", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.TeamMatchup", null)
                        .WithMany("MatchupRosterSpots")
                        .HasForeignKey("MatchupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matchup_roster_spots_team_matchups_matchup_id");

                    b.HasOne("FantasyHOF.Domain.Types.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matchup_roster_spots_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Player", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.FantasyProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_players_fantasy_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamMatchup", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.LeagueSeason", null)
                        .WithMany("Matchups")
                        .HasForeignKey("LeagueSeasonId")
                        .HasConstraintName("fk_team_matchups_league_seasons_league_season_id");

                    b.HasOne("FantasyHOF.Domain.Types.Team", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_matchups_teams_opponent_id");

                    b.HasOne("FantasyHOF.Domain.Types.Team", null)
                        .WithMany("Matchups")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_matchups_teams_team_id");

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamSeasonStats", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.Team", null)
                        .WithOne("SeasonStats")
                        .HasForeignKey("FantasyHOF.Domain.Types.TeamSeasonStats", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_season_stats_teams_team_id");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeason", b =>
                {
                    b.Navigation("LeagueSeasonMembers");

                    b.Navigation("Matchups");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonMember", b =>
                {
                    b.Navigation("LeagueSeasonMemberTeams");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonScoringSettings", b =>
                {
                    b.Navigation("ScoringItems");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.LeagueSeasonSettings", b =>
                {
                    b.Navigation("ScheduleSettings")
                        .IsRequired();

                    b.Navigation("ScoringSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.MatchupRosterSpot", b =>
                {
                    b.Navigation("AccumulatedStats");
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.Team", b =>
                {
                    b.Navigation("Matchups");

                    b.Navigation("SeasonStats")
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.TeamMatchup", b =>
                {
                    b.Navigation("MatchupRosterSpots");
                });
#pragma warning restore 612, 618
        }
    }
}
