// <auto-generated />
using FantasyHOF.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyHOF.EntityFramework.Migrations
{
    [DbContext(typeof(FantasyHOFDBContext))]
    partial class FantasyHOFDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyHOF.Domain.Types.FantasyProvider", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fantasy_provider");

                    b.ToTable("fantasy_provider", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FantasyProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("fantasy_provider_id");

                    b.Property<string>("ProviderLeagueId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_league_id");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.HasKey("Id")
                        .HasName("pk_leagues");

                    b.HasIndex("FantasyProviderId")
                        .HasDatabaseName("ix_leagues_fantasy_provider_id");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("FantasyHOF.Domain.Types.League", b =>
                {
                    b.HasOne("FantasyHOF.Domain.Types.FantasyProvider", "FantasyProvider")
                        .WithMany()
                        .HasForeignKey("FantasyProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leagues_fantasy_provider_fantasy_provider_id");

                    b.Navigation("FantasyProvider");
                });
#pragma warning restore 612, 618
        }
    }
}
