/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModeRouteRouteImport } from './routes/$mode/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeIndexRouteImport } from './routes/$mode/index'
import { Route as SportsFootballRouteImport } from './routes/sports/football'
import { Route as FeaturesSimpleImportsRouteImport } from './routes/features/simple-imports'
import { Route as FeaturesRecordsRouteImport } from './routes/features/records'
import { Route as ModeMyLeaguesRouteImport } from './routes/$mode/my-leagues'
import { Route as ModeLeagueIdRouteRouteImport } from './routes/$mode/$leagueId/route'
import { Route as ModeLeagueIdIndexRouteImport } from './routes/$mode/$leagueId/index'
import { Route as ModeLeagueIdDashboardRouteImport } from './routes/$mode/$leagueId/dashboard'
import { Route as ModeLeagueIdRecordTypeIdRouteImport } from './routes/$mode/$leagueId/$recordTypeId'

const ModeRouteRoute = ModeRouteRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeIndexRoute = ModeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeRouteRoute,
} as any)
const SportsFootballRoute = SportsFootballRouteImport.update({
  id: '/sports/football',
  path: '/sports/football',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSimpleImportsRoute = FeaturesSimpleImportsRouteImport.update({
  id: '/features/simple-imports',
  path: '/features/simple-imports',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRecordsRoute = FeaturesRecordsRouteImport.update({
  id: '/features/records',
  path: '/features/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeMyLeaguesRoute = ModeMyLeaguesRouteImport.update({
  id: '/my-leagues',
  path: '/my-leagues',
  getParentRoute: () => ModeRouteRoute,
} as any)
const ModeLeagueIdRouteRoute = ModeLeagueIdRouteRouteImport.update({
  id: '/$leagueId',
  path: '/$leagueId',
  getParentRoute: () => ModeRouteRoute,
} as any)
const ModeLeagueIdIndexRoute = ModeLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeLeagueIdRouteRoute,
} as any)
const ModeLeagueIdDashboardRoute = ModeLeagueIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ModeLeagueIdRouteRoute,
} as any)
const ModeLeagueIdRecordTypeIdRoute =
  ModeLeagueIdRecordTypeIdRouteImport.update({
    id: '/$recordTypeId',
    path: '/$recordTypeId',
    getParentRoute: () => ModeLeagueIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$mode': typeof ModeRouteRouteWithChildren
  '/$mode/$leagueId': typeof ModeLeagueIdRouteRouteWithChildren
  '/$mode/my-leagues': typeof ModeMyLeaguesRoute
  '/features/records': typeof FeaturesRecordsRoute
  '/features/simple-imports': typeof FeaturesSimpleImportsRoute
  '/sports/football': typeof SportsFootballRoute
  '/$mode/': typeof ModeIndexRoute
  '/$mode/$leagueId/$recordTypeId': typeof ModeLeagueIdRecordTypeIdRoute
  '/$mode/$leagueId/dashboard': typeof ModeLeagueIdDashboardRoute
  '/$mode/$leagueId/': typeof ModeLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$mode/my-leagues': typeof ModeMyLeaguesRoute
  '/features/records': typeof FeaturesRecordsRoute
  '/features/simple-imports': typeof FeaturesSimpleImportsRoute
  '/sports/football': typeof SportsFootballRoute
  '/$mode': typeof ModeIndexRoute
  '/$mode/$leagueId/$recordTypeId': typeof ModeLeagueIdRecordTypeIdRoute
  '/$mode/$leagueId/dashboard': typeof ModeLeagueIdDashboardRoute
  '/$mode/$leagueId': typeof ModeLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$mode': typeof ModeRouteRouteWithChildren
  '/$mode/$leagueId': typeof ModeLeagueIdRouteRouteWithChildren
  '/$mode/my-leagues': typeof ModeMyLeaguesRoute
  '/features/records': typeof FeaturesRecordsRoute
  '/features/simple-imports': typeof FeaturesSimpleImportsRoute
  '/sports/football': typeof SportsFootballRoute
  '/$mode/': typeof ModeIndexRoute
  '/$mode/$leagueId/$recordTypeId': typeof ModeLeagueIdRecordTypeIdRoute
  '/$mode/$leagueId/dashboard': typeof ModeLeagueIdDashboardRoute
  '/$mode/$leagueId/': typeof ModeLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$mode'
    | '/$mode/$leagueId'
    | '/$mode/my-leagues'
    | '/features/records'
    | '/features/simple-imports'
    | '/sports/football'
    | '/$mode/'
    | '/$mode/$leagueId/$recordTypeId'
    | '/$mode/$leagueId/dashboard'
    | '/$mode/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$mode/my-leagues'
    | '/features/records'
    | '/features/simple-imports'
    | '/sports/football'
    | '/$mode'
    | '/$mode/$leagueId/$recordTypeId'
    | '/$mode/$leagueId/dashboard'
    | '/$mode/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/$mode'
    | '/$mode/$leagueId'
    | '/$mode/my-leagues'
    | '/features/records'
    | '/features/simple-imports'
    | '/sports/football'
    | '/$mode/'
    | '/$mode/$leagueId/$recordTypeId'
    | '/$mode/$leagueId/dashboard'
    | '/$mode/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModeRouteRoute: typeof ModeRouteRouteWithChildren
  FeaturesRecordsRoute: typeof FeaturesRecordsRoute
  FeaturesSimpleImportsRoute: typeof FeaturesSimpleImportsRoute
  SportsFootballRoute: typeof SportsFootballRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$mode': {
      id: '/$mode'
      path: '/$mode'
      fullPath: '/$mode'
      preLoaderRoute: typeof ModeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$mode/': {
      id: '/$mode/'
      path: '/'
      fullPath: '/$mode/'
      preLoaderRoute: typeof ModeIndexRouteImport
      parentRoute: typeof ModeRouteRoute
    }
    '/sports/football': {
      id: '/sports/football'
      path: '/sports/football'
      fullPath: '/sports/football'
      preLoaderRoute: typeof SportsFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/simple-imports': {
      id: '/features/simple-imports'
      path: '/features/simple-imports'
      fullPath: '/features/simple-imports'
      preLoaderRoute: typeof FeaturesSimpleImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/records': {
      id: '/features/records'
      path: '/features/records'
      fullPath: '/features/records'
      preLoaderRoute: typeof FeaturesRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$mode/my-leagues': {
      id: '/$mode/my-leagues'
      path: '/my-leagues'
      fullPath: '/$mode/my-leagues'
      preLoaderRoute: typeof ModeMyLeaguesRouteImport
      parentRoute: typeof ModeRouteRoute
    }
    '/$mode/$leagueId': {
      id: '/$mode/$leagueId'
      path: '/$leagueId'
      fullPath: '/$mode/$leagueId'
      preLoaderRoute: typeof ModeLeagueIdRouteRouteImport
      parentRoute: typeof ModeRouteRoute
    }
    '/$mode/$leagueId/': {
      id: '/$mode/$leagueId/'
      path: '/'
      fullPath: '/$mode/$leagueId/'
      preLoaderRoute: typeof ModeLeagueIdIndexRouteImport
      parentRoute: typeof ModeLeagueIdRouteRoute
    }
    '/$mode/$leagueId/dashboard': {
      id: '/$mode/$leagueId/dashboard'
      path: '/dashboard'
      fullPath: '/$mode/$leagueId/dashboard'
      preLoaderRoute: typeof ModeLeagueIdDashboardRouteImport
      parentRoute: typeof ModeLeagueIdRouteRoute
    }
    '/$mode/$leagueId/$recordTypeId': {
      id: '/$mode/$leagueId/$recordTypeId'
      path: '/$recordTypeId'
      fullPath: '/$mode/$leagueId/$recordTypeId'
      preLoaderRoute: typeof ModeLeagueIdRecordTypeIdRouteImport
      parentRoute: typeof ModeLeagueIdRouteRoute
    }
  }
}

interface ModeLeagueIdRouteRouteChildren {
  ModeLeagueIdRecordTypeIdRoute: typeof ModeLeagueIdRecordTypeIdRoute
  ModeLeagueIdDashboardRoute: typeof ModeLeagueIdDashboardRoute
  ModeLeagueIdIndexRoute: typeof ModeLeagueIdIndexRoute
}

const ModeLeagueIdRouteRouteChildren: ModeLeagueIdRouteRouteChildren = {
  ModeLeagueIdRecordTypeIdRoute: ModeLeagueIdRecordTypeIdRoute,
  ModeLeagueIdDashboardRoute: ModeLeagueIdDashboardRoute,
  ModeLeagueIdIndexRoute: ModeLeagueIdIndexRoute,
}

const ModeLeagueIdRouteRouteWithChildren =
  ModeLeagueIdRouteRoute._addFileChildren(ModeLeagueIdRouteRouteChildren)

interface ModeRouteRouteChildren {
  ModeLeagueIdRouteRoute: typeof ModeLeagueIdRouteRouteWithChildren
  ModeMyLeaguesRoute: typeof ModeMyLeaguesRoute
  ModeIndexRoute: typeof ModeIndexRoute
}

const ModeRouteRouteChildren: ModeRouteRouteChildren = {
  ModeLeagueIdRouteRoute: ModeLeagueIdRouteRouteWithChildren,
  ModeMyLeaguesRoute: ModeMyLeaguesRoute,
  ModeIndexRoute: ModeIndexRoute,
}

const ModeRouteRouteWithChildren = ModeRouteRoute._addFileChildren(
  ModeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModeRouteRoute: ModeRouteRouteWithChildren,
  FeaturesRecordsRoute: FeaturesRecordsRoute,
  FeaturesSimpleImportsRoute: FeaturesSimpleImportsRoute,
  SportsFootballRoute: SportsFootballRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
