/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoLayoutRouteImport } from './routes/demo/_layout'
import { Route as DemoLayoutIndexRouteImport } from './routes/demo/_layout/index'
import { Route as DemoLayoutLeagueIdRouteImport } from './routes/demo/_layout/$leagueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLayoutRoute = DemoLayoutRouteImport.update({
  id: '/demo/_layout',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLayoutIndexRoute = DemoLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoLayoutRoute,
} as any)
const DemoLayoutLeagueIdRoute = DemoLayoutLeagueIdRouteImport.update({
  id: '/$leagueId',
  path: '/$leagueId',
  getParentRoute: () => DemoLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoLayoutRouteWithChildren
  '/demo/$leagueId': typeof DemoLayoutLeagueIdRoute
  '/demo/': typeof DemoLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/$leagueId': typeof DemoLayoutLeagueIdRoute
  '/demo': typeof DemoLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/_layout': typeof DemoLayoutRouteWithChildren
  '/demo/_layout/$leagueId': typeof DemoLayoutLeagueIdRoute
  '/demo/_layout/': typeof DemoLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/demo/$leagueId' | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/$leagueId' | '/demo'
  id:
    | '__root__'
    | '/'
    | '/demo/_layout'
    | '/demo/_layout/$leagueId'
    | '/demo/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoLayoutRoute: typeof DemoLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/_layout': {
      id: '/demo/_layout'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/_layout/': {
      id: '/demo/_layout/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoLayoutIndexRouteImport
      parentRoute: typeof DemoLayoutRoute
    }
    '/demo/_layout/$leagueId': {
      id: '/demo/_layout/$leagueId'
      path: '/$leagueId'
      fullPath: '/demo/$leagueId'
      preLoaderRoute: typeof DemoLayoutLeagueIdRouteImport
      parentRoute: typeof DemoLayoutRoute
    }
  }
}

interface DemoLayoutRouteChildren {
  DemoLayoutLeagueIdRoute: typeof DemoLayoutLeagueIdRoute
  DemoLayoutIndexRoute: typeof DemoLayoutIndexRoute
}

const DemoLayoutRouteChildren: DemoLayoutRouteChildren = {
  DemoLayoutLeagueIdRoute: DemoLayoutLeagueIdRoute,
  DemoLayoutIndexRoute: DemoLayoutIndexRoute,
}

const DemoLayoutRouteWithChildren = DemoLayoutRoute._addFileChildren(
  DemoLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoLayoutRoute: DemoLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
