/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoLayoutRouteImport } from './routes/demo/_layout'
import { Route as DemoLayoutFootballRouteImport } from './routes/demo/_layout/football'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLayoutRoute = DemoLayoutRouteImport.update({
  id: '/demo/_layout',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLayoutFootballRoute = DemoLayoutFootballRouteImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => DemoLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoLayoutRouteWithChildren
  '/demo/football': typeof DemoLayoutFootballRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoLayoutRouteWithChildren
  '/demo/football': typeof DemoLayoutFootballRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/_layout': typeof DemoLayoutRouteWithChildren
  '/demo/_layout/football': typeof DemoLayoutFootballRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/demo/football'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/demo/football'
  id: '__root__' | '/' | '/demo/_layout' | '/demo/_layout/football'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoLayoutRoute: typeof DemoLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/_layout': {
      id: '/demo/_layout'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/_layout/football': {
      id: '/demo/_layout/football'
      path: '/football'
      fullPath: '/demo/football'
      preLoaderRoute: typeof DemoLayoutFootballRouteImport
      parentRoute: typeof DemoLayoutRoute
    }
  }
}

interface DemoLayoutRouteChildren {
  DemoLayoutFootballRoute: typeof DemoLayoutFootballRoute
}

const DemoLayoutRouteChildren: DemoLayoutRouteChildren = {
  DemoLayoutFootballRoute: DemoLayoutFootballRoute,
}

const DemoLayoutRouteWithChildren = DemoLayoutRoute._addFileChildren(
  DemoLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoLayoutRoute: DemoLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
